main: crypto_project_tiktok.Main
name: TikTokker
version: 1.1
api-version: 1.13
author: Christian Frandsen
description: TikTokking in Minecraft
commands:
   rtp:
       description: Random teleport up
       usage: /rtp
       permission: tiktokker.tik
       permission-message: You don't have the tiktokker.tik permission.
   multiplier:
       description: Nuvrrende multiplier
       usage: multiplier
       permission: tiktokker.tik.tok
       permission-message: You don't have the tiktokker.tik.tok permission.
   disable:
       description: Disable multiplier
       usage: disable
       permission: tiktokker.tik.tok
       permission-message: You don't have the tiktokker.tik.tok permission.